replicaCount: 1
applicationName: aksworkshop

image:
  repository: order
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

configmap: true

env:
  values: {}
