{{- $name := include "aw-order.fullname" . -}}

{{- if .Values.env.secretmap -}}
apiVersion: v1
kind: Secret
metadata:
  name: "scr-{{ $name }}"
  labels:
    app: {{ template "aw-order.name" . }}
    chart: {{ template "aw-order.chart" .}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  constr: {{ .Values.order.constr | b64enc }}
{{- end -}}