apiVersion: v1
kind: Service
metadata:
  labels:
    app: aksworksop
    component: basket
  name: basket
spec:
  ports:
  - port: {{ .Values.service.port }}
    name: http
    targetPort: http
  - port: {{ .Values.service.grpcPort }}
    name: grpc
    targetPort: grpc
  selector:
    app: aksworksop
    component: basket
