apiVersion: apps/v1
kind: Deployment
metadata:
  name: basket  
spec:
  selector:
    matchLabels:
      app: aksworksop
      component: basket 
  template:
    metadata:
      labels:
        app: aksworksop
        component: basket
    spec:
      containers:
      - name: basket
        image: {{ .Values.image.registry }}/basket:{{ .Values.image.tag }}
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: basket
        ports:
        - containerPort: {{ .Values.deployment.port }}
          name: http
        - containerPort: {{ .Values.deployment.grpcPort }}
          name: grpc
#      imagePullSecrets:
#      - name: acr-key
