{{- $name := include "aw-catalog.fullname" . -}}

{{- if .Values.env.secretmap -}}
apiVersion: v1
kind: Secret
metadata:
  name: "scr-{{ $name }}"
  labels:
    app: {{ template "aw-catalog.name" . }}
    chart: {{ template "aw-catalog.chart" .}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  constr: {{ .Values.catalog.constr  | b64enc }} 
{{- end -}}