apiVersion: v1
kind: Service
metadata:
  name: catalog
  labels:
    app: aksworkshop
    chart: {{ template "aw-catalog.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "aw-catalog.name" . }}
    release: {{ .Release.Name }}
