apiVersion: v1
kind: Service
metadata:
  labels:
    app: aksworksop
    component: basket
  name: basket
spec:
  ports:
  - port: 80
    name: http
    targetPort: http
  - port: 81
    name: grpc
    targetPort: grpc
  selector:
    app: aksworksop
    component: basket
