version: '3.4'

services:
  apiserver:
    image: ${DOCKER_REGISTRY-}apiserver
    build:
      context: .
      dockerfile: ApiServer/Dockerfile

  webclient:
    image: ${DOCKER_REGISTRY-}webclient
    build:
      context: .
      dockerfile: WebClient/Dockerfile

